name: parkingsmart
description: UI khung 3 tab + chart 5 ngày
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.68.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.4.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.4.4
  firebase_database: ^11.1.3

flutter:
  uses-material-design: true
